include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  errors:
    specify_nonobvious_property_types: ignore
  exclude:
    - lib/l10n/generated/*
    - lib/generated/*
    - lib/**/*.g.dart
    - assets/**/*.gen.dart
    - packages/**/*.gen.dart
linter:
  rules:
    public_member_api_docs: false
    document_ignores: false
    avoid_catches_without_on_clauses: false
    use_null_aware_elements: true
formatter:
  page_width: 80
