include: package:very_good_analysis/analysis_options.9.0.0.yaml
analyzer:
  exclude:
    - lib/l10n/*
    - lib/generated/*
    - lib/**/*.g.dart
    - assets/**/*.gen.dart
    - packages/**/*.gen.dart
linter:
  rules:
    document_ignores: false
    avoid_catches_without_on_clauses: false
