include: package:very_good_analysis/analysis_options.9.0.0.yaml
analyzer:
  errors:
    avoid_redundant_argument_values: ignore
    specify_nonobvious_property_types: ignore
linter:
  rules:
    document_ignores: false
    avoid_catches_without_on_clauses: false
    use_null_aware_elements: true
